image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

environment:
  matrix:
  - PYTHON: 37
    CPP: 14
    CONFIG: Debug

build_script:
  - mkdir build
  - cd build
  - cmake c:\works\cppdrill -G "Visual Studio 15"
  - cmake --build . --config Debug
