image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

configuration:
  - Release
  - Debug

environment:
  - PYTHON: 'C:\\Python37'
  
# install:
#   - dir C:

build_script:
  - echo %CONFIGURATION%
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - echo %PYTHON%
  - set PATH=%PYTHON%;%PATH%
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build . --config %CONFIGURATION%

test_script:
  - echo %CONFIGURATION%
  - ctest -C %CONFIGURATION%
