image:
  - Visual Studio 2019

build:
  parallel: true

platform:
- x64

configuration:
  - Release
  - Debug

environment:
  matrix:
  - PYTHON: 37
    CPP: 14

build_script:
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - mkdir build
  - cd build
  - echo "CONFIGURATION %CONFIGURATION%"
  - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "Visual Studio 16"
  - cmake --build . --config %CONFIGURATION%

on_failure:
  - type "C:\projects\cppdrill\build\CMakeFiles\CMakeOutput.log"

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\mylib_test.exe'