image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

environment:
  matrix:
  - PYTHON: 37
    CPP: 14

build_script:
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 15"
  - cmake --build . --config Debug
