image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

configuration:
  - Release
  - Debug

install:
  - dir C:

build_script:
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build . --config %CONFIG%

test_script:
  - ctest -C %CONFIG%
