image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

configuration:
  - Release
  - Debug

environment:
  matrix:
    - PYTHON: C:\Python37

build_script:
  - echo %CONFIGURATION%
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - set PATH=%PYTHON%;%PATH%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DTBB_BUILD_STATIC=OFF -DTBB_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=%CONFIGURATION%
  - cmake --build . --config %CONFIGURATION%

test_script:
  - echo %CONFIGURATION%
  - bin/%CONFIGURATION%/test_all.exe
