image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

configuration:
  - Release
  - Debug

environment:
  matrix:
    - PYTHON: C:\Python37

install:
  - dir c:\cygwin
  - dir c:\cygwin64
  - dir c:\mingw-w64
  - dir c:\msys64
  - dir c:\Tools

  # for TBB
  - copy C:\msys64\mingw64\bin\mingw32-make.exe C:\msys64\mingw64\bin\gmake.exe
  - copy c:\ProgramData\chocolatey\bin\make.exe c:\ProgramData\chocolatey\bin\gmake.exe

build_script:
  - echo %CONFIGURATION%
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - set PATH=%PYTHON%;%PATH%
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - echo %CONFIGURATION%
  - ctest -C %CONFIGURATION%
