image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

configuration:
  - Release
  - Debug

environment:
  matrix:
    - PYTHON: C:\Python37

install:
  - echo %PATH%
  - dir c:\cygwin\bin
  - dir c:\cygwin64\bin

  # for TBB
  - copy C:\msys64\mingw64\bin\mingw32-make.exe C:\msys64\mingw64\bin\gmake.exe

build_script:
  - echo %CONFIGURATION%
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - set PATH=%PYTHON%;%PATH%
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - echo %CONFIGURATION%
  - ctest -C %CONFIGURATION%
