image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

configuration:
  - Release
  - Debug

# environment:
#   matrix:
#   - PYTHON: 37
#     CPP: 14

build_script:
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build . --config %CONFIG%

test_script:
  - cd # for pwd
  - cd build
  - ctest -C %CONFIG%
