image:
  - Visual Studio 2017

build:
  parallel: true

platform:
- x64
- x86

configuration:
  - Release
  - Debug

install:
  - dir C:

build_script:
  - echo %CONFIG%
  - echo %CONFIGURATION%
  - echo $(CONFIG)
  - echo $(CONFIGURATION)
  - cd externals
  - git submodule update --init --recursive
  - cd ..
  - mkdir build
  - cd build
  - cmake .. 
  - cmake --build . --config %CONFIG%

test_script:
  - echo %CONFIG%
  - echo %CONFIGURATION%
  - echo $(CONFIG)
  - echo $(CONFIGURATION)
  - ctest -C %CONFIG%
