language: generic

matrix:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      before_install:
        - pyenv global 3.7.1

    - name: "macOS"
      os: osx
      osx_image: xcode11
      python: "3.7"
      before_install:
      # Missing /usr/include somtimes..
      - sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. -DTBB_BUILD_STATIC=OFF -DTBB_BUILD_TESTS=OFF
  - cmake --build . --parallel 2
  - bin/test_all
