language: cpp

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - name: "Bionic Linux"
      os: linux
      dist: bionic
      # script:
      #  - sudo apt-get install -y cmake python3 python3-dev

    - name: "macOS"
      os: osx
      osx_image: xcode11

    - name: "Windows"
      os: windows


script:
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
