language: cpp
env: OS_PYTHON_VERSIONS=3.7
python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - name: "Python on Bionic Linux"
      os: linux
      dist: bionic
      script:
        - sudo apt-get install -y cmake python3 python3-dev

    - name: "Python on macOS"
      os: osx
      osx_image: xcode11
      # script:
        # - brew update
        # - brew install cmake


script:
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
