language: cpp
env: OS_PYTHON_VERSIONS=3.7

matrix:
  include:
    - name: "Python 3.7 on Bionic Linux"
      os: linux
      dist: bionic
      script:
        - sudo apt-get install -y cmake python3 python3-dev

    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11
      # script:
        # - brew update
        # - brew install cmake


script:
  - pyenv global 3.7.1
  - cd build
  - cmake ..
  - cmake --build . -- -j2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
