language: generic

matrix:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      before_install:
        - pyenv global 3.7.1

    - name: "macOS"
      os: osx
      osx_image: xcode11
      python: "3.7"

script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --parallel 2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
