language: python

python:
  - "3.6"

matrix:
  include:
    - name: "Linux"
      os: linux
      dist: bionic
      # before_install:
      #   - pyenv global 3.7.1
      # script:
      #  - sudo apt-get install -y cmake python3 python3-dev

    - name: "macOS"
      os: osx
      osx_image: xcode11

    # - name: "Windows"
    #   os: windows
    #   env: CMAKE_BUILD_TYPE=Release
    #   before_install:
    #     - choco install python3
    #     - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    #   after_failure:
    #     - type C:/Users/travis/build/haje01/cppdrill/build/CMakeFiles/CMakeOutput.log



script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --parallel 2
  - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
