language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      env: OS_PYTHON_VERSIONS=3.7

script:
  - sudo apt-get install -y cmake python3 python3-dev
  # - pyenv global 3.7.1
  - cd build
#   - cmake .. -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.7
  - cmake ..
  - cmake --build . -- -j2
  - make test
