language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      env: OS_PYTHON_VERSIONS=3.6

script:
  - sudo apt-get install -y cmake python3
  - cd build
  - cmake ..
  - cmake --build . -- -j2